// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: demo

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_border_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen2, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 800);
    lv_obj_set_height(ui_Container3, 300);
    lv_obj_set_x(ui_Container3, 1);
    lv_obj_set_y(ui_Container3, -35);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_speed = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_speed, 300);
    lv_obj_set_height(ui_speed, 300);
    lv_obj_set_align(ui_speed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_speed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_speed, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_speed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_speed, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_speed_arc = lv_arc_create(ui_speed);
    lv_obj_set_width(ui_speed_arc, 300);
    lv_obj_set_height(ui_speed_arc, 300);
    lv_obj_set_align(ui_speed_arc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_speed_arc, 50);
    lv_obj_set_style_border_width(ui_speed_arc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_speed_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speed_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_speed_num = lv_label_create(ui_speed);
    lv_obj_set_width(ui_speed_num, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speed_num, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speed_num, 0);
    lv_obj_set_y(ui_speed_num, -10);
    lv_obj_set_align(ui_speed_num, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speed_num, "50");
    lv_obj_set_style_text_color(ui_speed_num, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speed_num, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speed_num, &ui_font_Jersey80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speed_label = lv_label_create(ui_speed);
    lv_obj_set_width(ui_speed_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speed_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speed_label, 0);
    lv_obj_set_y(ui_speed_label, 80);
    lv_obj_set_align(ui_speed_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speed_label, "Km/h");
    lv_obj_set_style_text_color(ui_speed_label, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speed_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speed_label, &ui_font_PoetsenOne40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gear = lv_label_create(ui_speed);
    lv_obj_set_width(ui_gear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gear, 0);
    lv_obj_set_y(ui_gear, -91);
    lv_obj_set_align(ui_gear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gear, "N");
    lv_obj_set_style_text_color(ui_gear, lv_color_hex(0x208BE3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gear, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel4, 200);
    lv_obj_set_height(ui_Panel4, 200);
    lv_obj_set_x(ui_Panel4, -260);
    lv_obj_set_y(ui_Panel4, 0);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc2 = lv_arc_create(ui_Panel4);
    lv_obj_set_width(ui_Arc2, 200);
    lv_obj_set_height(ui_Arc2, 200);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc2, 0, 7000);
    lv_arc_set_value(ui_Arc2, 50);
    lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 60);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "RPM");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_PoetsenOne20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LRPM = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_LRPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LRPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LRPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LRPM, "0000");
    lv_obj_set_style_text_color(ui_LRPM, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LRPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LRPM, &ui_font_Jersey40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel5, 200);
    lv_obj_set_height(ui_Panel5, 200);
    lv_obj_set_x(ui_Panel5, 260);
    lv_obj_set_y(ui_Panel5, 0);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc3 = lv_arc_create(ui_Panel5);
    lv_obj_set_width(ui_Arc3, 200);
    lv_obj_set_height(ui_Arc3, 200);
    lv_obj_set_x(ui_Arc3, 0);
    lv_obj_set_y(ui_Arc3, 1);
    lv_obj_set_align(ui_Arc3, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc3, 0, 7000);
    lv_arc_set_value(ui_Arc3, 50);

    lv_obj_set_style_bg_color(ui_Arc3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, 60);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "RPM");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_PoetsenOne20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RRPM = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_RRPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RRPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RRPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RRPM, "0000");
    lv_obj_set_style_text_color(ui_RRPM, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RRPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RRPM, &ui_font_Jersey40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_power_battery = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_power_battery, 250);
    lv_obj_set_height(ui_power_battery, 70);
    lv_obj_set_x(ui_power_battery, -164);
    lv_obj_set_y(ui_power_battery, 149);
    lv_obj_set_align(ui_power_battery, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_power_battery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_power_battery, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_power_battery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_power_battery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_power_battery_Label = lv_label_create(ui_power_battery);
    lv_obj_set_width(ui_power_battery_Label, LV_SIZE_CONTENT);   /// -17
    lv_obj_set_height(ui_power_battery_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_power_battery_Label, -6);
    lv_obj_set_y(ui_power_battery_Label, -7);
    lv_obj_set_align(ui_power_battery_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_power_battery_Label, "0%");
    lv_obj_set_style_text_color(ui_power_battery_Label, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_power_battery_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_power_battery_Slider = lv_slider_create(ui_power_battery);
    lv_slider_set_value(ui_power_battery_Slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_power_battery_Slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_power_battery_Slider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_power_battery_Slider, 150);
    lv_obj_set_height(ui_power_battery_Slider, 10);
    lv_obj_set_x(ui_power_battery_Slider, 40);
    lv_obj_set_y(ui_power_battery_Slider, 13);
    lv_obj_set_align(ui_power_battery_Slider, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_power_battery_Slider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_power_battery_Slider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_power_battery_icon = lv_img_create(ui_power_battery);
    lv_img_set_src(ui_power_battery_icon, &ui_img_h_battery_png);
    lv_obj_set_width(ui_power_battery_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_power_battery_icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_power_battery_icon, -80);
    lv_obj_set_y(ui_power_battery_icon, 0);
    lv_obj_set_align(ui_power_battery_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_power_battery_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_power_battery_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_battery = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_battery, &ui_img_battery_png);
    lv_obj_set_width(ui_battery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_battery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_battery, 290);
    lv_obj_set_y(ui_battery, -210);
    lv_obj_set_align(ui_battery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_battery, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_battery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_internet = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_internet, &ui_img_internet_network_png);
    lv_obj_set_width(ui_internet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_internet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_internet, 259);
    lv_obj_set_y(ui_internet, 151);
    lv_obj_set_align(ui_internet, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_internet, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_internet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LmotorTem = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LmotorTem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LmotorTem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LmotorTem, -300);
    lv_obj_set_y(ui_LmotorTem, 80);
    lv_obj_set_align(ui_LmotorTem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LmotorTem, "25");
    lv_obj_set_style_text_color(ui_LmotorTem, lv_color_hex(0x2FD3A2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LmotorTem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LmotorTem, &ui_font_jersey30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LmcuTem = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LmcuTem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LmcuTem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LmcuTem, -220);
    lv_obj_set_y(ui_LmcuTem, 80);
    lv_obj_set_align(ui_LmcuTem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LmcuTem, "26");
    lv_obj_set_style_text_color(ui_LmcuTem, lv_color_hex(0x28CA9C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LmcuTem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LmcuTem, &ui_font_jersey30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RmotorTem = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_RmotorTem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RmotorTem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RmotorTem, 220);
    lv_obj_set_y(ui_RmotorTem, 80);
    lv_obj_set_align(ui_RmotorTem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RmotorTem, "25");
    lv_obj_set_style_text_color(ui_RmotorTem, lv_color_hex(0x29CA9C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RmotorTem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RmotorTem, &ui_font_jersey30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RmcuTem = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_RmcuTem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RmcuTem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RmcuTem, 300);
    lv_obj_set_y(ui_RmcuTem, 80);
    lv_obj_set_align(ui_RmcuTem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RmcuTem, "26");
    lv_obj_set_style_text_color(ui_RmcuTem, lv_color_hex(0x29D2A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RmcuTem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RmcuTem, &ui_font_jersey30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lyracingteam = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_lyracingteam, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lyracingteam, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lyracingteam, -7);
    lv_obj_set_y(ui_lyracingteam, 210);
    lv_obj_set_align(ui_lyracingteam, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lyracingteam, "LingYunRacingTeam");
    lv_obj_set_style_text_color(ui_lyracingteam, lv_color_hex(0xDE3439), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lyracingteam, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lyracingteam, &ui_font_fasterone20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Hbattery_allert = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Hbattery_allert, &ui_img_battery_allert_png);
    lv_obj_set_width(ui_Hbattery_allert, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Hbattery_allert, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Hbattery_allert, 350);
    lv_obj_set_y(ui_Hbattery_allert, -210);
    lv_obj_set_align(ui_Hbattery_allert, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Hbattery_allert, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Hbattery_allert, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_speed_arc, ui_event_speed_arc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Arc2, ui_event_Arc2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Arc3, ui_event_Arc3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_power_battery_Slider, ui_event_power_battery_Slider, LV_EVENT_ALL, NULL);

}
