// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: demo

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Image25;
void ui_event_Slider2(lv_event_t * e);
lv_obj_t * ui_Slider2;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Container3;
lv_obj_t * ui_speed;
void ui_event_speed_arc(lv_event_t * e);
lv_obj_t * ui_speed_arc;
lv_obj_t * ui_speed_num;
lv_obj_t * ui_speed_label;
lv_obj_t * ui_gear;
lv_obj_t * ui_Panel4;
void ui_event_Arc2(lv_event_t * e);
lv_obj_t * ui_Arc2;
lv_obj_t * ui_Label6;
lv_obj_t * ui_LRPM;
lv_obj_t * ui_Panel5;
void ui_event_Arc3(lv_event_t * e);
lv_obj_t * ui_Arc3;
lv_obj_t * ui_Label7;
lv_obj_t * ui_RRPM;
lv_obj_t * ui_power_battery;
lv_obj_t * ui_power_battery_Label;
void ui_event_power_battery_Slider(lv_event_t * e);
lv_obj_t * ui_power_battery_Slider;
lv_obj_t * ui_power_battery_icon;
lv_obj_t * ui_battery;
lv_obj_t * ui_internet;
lv_obj_t * ui_LmotorTem;
lv_obj_t * ui_LmcuTem;
lv_obj_t * ui_RmotorTem;
lv_obj_t * ui_RmcuTem;
lv_obj_t * ui_lyracingteam;
lv_obj_t * ui_Hbattery_allert;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_speed_arc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_speed_num, target, "", "");
    }
}
void ui_event_Arc2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LRPM, target, "", "");
    }
}
void ui_event_Arc3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_RRPM, target, "", "");
    }
}
void ui_event_power_battery_Slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_power_battery_Label, target, "", "%");
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
