// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "Variable.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_main_sreen
void ui_main_sreen_screen_init(void);
lv_obj_t * ui_main_sreen;
lv_obj_t * ui_L_RPM;
lv_obj_t * ui_R_RPM;
lv_obj_t * ui_SPEED;
lv_obj_t * ui_L_Mot_Tem;
lv_obj_t * ui_L_MCU_Tem;
lv_obj_t * ui_R_Mot_Tem;
lv_obj_t * ui_R_MCU_Tem;
lv_obj_t * ui_CAR_Mode;
lv_obj_t * ui_SOC;
lv_obj_t * ui_time_used;
lv_obj_t * ui_lap_time;
lv_obj_t * ui_best_time;
lv_obj_t * ui_L_Battery_Alr;
lv_obj_t * ui_Iot;
void ui_event_Sliderspeed(lv_event_t * e);
lv_obj_t * ui_Sliderspeed;
void ui_event_SliderSOC(lv_event_t * e);
lv_obj_t * ui_SliderSOC;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Image10;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Image12;
lv_obj_t * ui_Image13;
lv_obj_t * ui_Image14;
lv_obj_t * ui_Image15;


// SCREEN: ui_startup
void ui_startup_screen_init(void);
lv_obj_t * ui_startup;
lv_obj_t * ui_LYicon;
lv_obj_t * ui_LYlabel;
void ui_event_Sliderstartup(lv_event_t * e);
lv_obj_t * ui_Sliderstartup;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_group_[2] = {&ui_img_group_4_png, &ui_img_group_5_png};
const lv_img_dsc_t * ui_imgset_line[6] = {&ui_img_line1_png, &ui_img_line2_png, &ui_img_line3_png, &ui_img_line4_png, &ui_img_line5_png, &ui_img_line6_png};

//USER DEFINE
uint32_t SLIDER_LOAD_OVER;
uint32_t MQTT_INIT_OK;
uint8_t barFlag = 1;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Sliderspeed(lv_event_t * e)
{
     lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_SPEED, target, "", "");
    }
}
void ui_event_SliderSOC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_SOC, target, "", "%");
    }
}
void ui_event_Sliderstartup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == SLIDER_LOAD_OVER) {
        _ui_screen_change(&ui_main_sreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_main_sreen_screen_init);
    }
}

void sendEventCode()
{
	if(lv_bar_get_value(ui_Sliderstartup) == 100)
	{
		barFlag = 0; //    ??0?        ??    
		lv_event_send(ui_Sliderstartup, SLIDER_LOAD_OVER, NULL);
	}
}

void ui_event_internet_icon(lv_event_t * e){
	lv_event_code_t event_code = lv_event_get_code(e);
	lv_obj_t * target = lv_event_get_target(e);
	if(event_code == MQTT_INIT_OK){
		if(MQTTClient_RdyFlag){
			lv_obj_clear_flag(ui_Iot, LV_OBJ_FLAG_HIDDEN);
		}
		else{
			lv_obj_add_flag(ui_Iot, LV_OBJ_FLAG_HIDDEN);
		}
	}
}
///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_main_sreen_screen_init();
    ui_startup_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_startup);
}
