// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_main_sreen
void ui_main_sreen_screen_init(void);
extern lv_obj_t * ui_main_sreen;
extern lv_obj_t * ui_L_RPM;
extern lv_obj_t * ui_R_RPM;
extern lv_obj_t * ui_SPEED;
extern lv_obj_t * ui_L_Mot_Tem;
extern lv_obj_t * ui_L_MCU_Tem;
extern lv_obj_t * ui_R_Mot_Tem;
extern lv_obj_t * ui_R_MCU_Tem;
extern lv_obj_t * ui_CAR_Mode;
extern lv_obj_t * ui_SOC;
extern lv_obj_t * ui_time_used;
extern lv_obj_t * ui_lap_time;
extern lv_obj_t * ui_best_time;
extern lv_obj_t * ui_L_Battery_Alr;
extern lv_obj_t * ui_Iot;
void ui_event_Sliderspeed(lv_event_t * e);
extern lv_obj_t * ui_Sliderspeed;
void ui_event_SliderSOC(lv_event_t * e);
extern lv_obj_t * ui_SliderSOC;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Image15;
// SCREEN: ui_startup
void ui_startup_screen_init(void);
extern lv_obj_t * ui_startup;
extern lv_obj_t * ui_LYicon;
extern lv_obj_t * ui_LYlabel;
void ui_event_Sliderstartup(lv_event_t * e);
extern lv_obj_t * ui_Sliderstartup;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_2095113354);    // assets/charging-battery.png
LV_IMG_DECLARE(ui_img_iot_png);    // assets/iot.png
LV_IMG_DECLARE(ui_img_guage_bg_png);    // assets/guage bg.png
LV_IMG_DECLARE(ui_img_group_4_png);    // assets/Group 4.png
LV_IMG_DECLARE(ui_img_group_5_png);    // assets/Group 5.png
LV_IMG_DECLARE(ui_img_line1_png);    // assets/line1.png
LV_IMG_DECLARE(ui_img_line2_png);    // assets/line2.png
LV_IMG_DECLARE(ui_img_line3_png);    // assets/line3.png
LV_IMG_DECLARE(ui_img_line4_png);    // assets/line4.png
LV_IMG_DECLARE(ui_img_line5_png);    // assets/line5.png
LV_IMG_DECLARE(ui_img_line6_png);    // assets/line6.png
LV_IMG_DECLARE(ui_img_ly_icon_png);    // assets/ly_icon.png



LV_FONT_DECLARE(ui_font_Anton_75_bpp4);
LV_FONT_DECLARE(ui_font_Anton_bpp4_35);
LV_FONT_DECLARE(ui_font_Anton_bpp4_40);
LV_FONT_DECLARE(ui_font_mashanzheng_60_bpp4);

extern uint8_t barFlag;

extern uint32_t SLIDER_LOAD_OVER;
extern uint32_t MQTT_INIT_OK;

void ui_init(void);
void sendEventCode(void);
void ui_event_internet_icon(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
