// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: demo

#ifndef _DEMO_UI_H
#define _DEMO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Image25;
void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_speed;
void ui_event_speed_arc(lv_event_t * e);
extern lv_obj_t * ui_speed_arc;
extern lv_obj_t * ui_speed_num;
extern lv_obj_t * ui_speed_label;
extern lv_obj_t * ui_gear;
extern lv_obj_t * ui_Panel4;
void ui_event_Arc2(lv_event_t * e);
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_LRPM;
extern lv_obj_t * ui_Panel5;
void ui_event_Arc3(lv_event_t * e);
extern lv_obj_t * ui_Arc3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_RRPM;
extern lv_obj_t * ui_power_battery;
extern lv_obj_t * ui_power_battery_Label;
void ui_event_power_battery_Slider(lv_event_t * e);
extern lv_obj_t * ui_power_battery_Slider;
extern lv_obj_t * ui_power_battery_icon;
extern lv_obj_t * ui_battery;
extern lv_obj_t * ui_internet;
extern lv_obj_t * ui_LmotorTem;
extern lv_obj_t * ui_LmcuTem;
extern lv_obj_t * ui_RmotorTem;
extern lv_obj_t * ui_RmcuTem;
extern lv_obj_t * ui_lyracingteam;
extern lv_obj_t * ui_Hbattery_allert;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_ly_icon_png);    // assets/ly_icon.png
LV_IMG_DECLARE(ui_img_h_battery_png);    // assets/H_battery.png
LV_IMG_DECLARE(ui_img_battery_png);    // assets/battery.png
LV_IMG_DECLARE(ui_img_internet_network_png);    // assets/internet_network.png
LV_IMG_DECLARE(ui_img_battery_allert_png);    // assets/battery_allert.png



LV_FONT_DECLARE(ui_font_fasterone20);
LV_FONT_DECLARE(ui_font_Font40s4pbpp);
LV_FONT_DECLARE(ui_font_jersey30);
LV_FONT_DECLARE(ui_font_Jersey40);
LV_FONT_DECLARE(ui_font_Jersey80);
LV_FONT_DECLARE(ui_font_PoetsenOne20);
LV_FONT_DECLARE(ui_font_PoetsenOne40);


extern uint8_t barFlag;

extern uint32_t SLIDER_LOAD_OVER;

void ui_init(void);
void sendEventCode();

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
