// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_main_sreen_screen_init(void)
{
    ui_main_sreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_main_sreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_main_sreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main_sreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_L_RPM = lv_label_create(ui_main_sreen);
    lv_obj_set_width(ui_L_RPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_L_RPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_L_RPM, -250);
    lv_obj_set_y(ui_L_RPM, -150);
    lv_obj_set_align(ui_L_RPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_L_RPM, "0000");
    lv_obj_set_style_text_color(ui_L_RPM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_L_RPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_L_RPM, &ui_font_Anton_bpp4_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_R_RPM = lv_label_create(ui_main_sreen);
    lv_obj_set_width(ui_R_RPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_R_RPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_R_RPM, 250);
    lv_obj_set_y(ui_R_RPM, -150);
    lv_obj_set_align(ui_R_RPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_R_RPM, "0000");
    lv_obj_set_style_text_color(ui_R_RPM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_R_RPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_R_RPM, &ui_font_Anton_bpp4_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SPEED = lv_label_create(ui_main_sreen);
    lv_obj_set_width(ui_SPEED, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SPEED, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SPEED, 2);
    lv_obj_set_y(ui_SPEED, -110);
    lv_obj_set_align(ui_SPEED, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SPEED, "00");
    lv_obj_set_style_text_color(ui_SPEED, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SPEED, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SPEED, &ui_font_Anton_75_bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_L_Mot_Tem = lv_label_create(ui_main_sreen);
    lv_obj_set_width(ui_L_Mot_Tem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_L_Mot_Tem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_L_Mot_Tem, -310);
    lv_obj_set_y(ui_L_Mot_Tem, -80);
    lv_obj_set_align(ui_L_Mot_Tem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_L_Mot_Tem, "00");
    lv_obj_set_style_text_color(ui_L_Mot_Tem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_L_Mot_Tem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_L_Mot_Tem, &ui_font_Anton_bpp4_35, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_L_MCU_Tem = lv_label_create(ui_main_sreen);
    lv_obj_set_width(ui_L_MCU_Tem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_L_MCU_Tem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_L_MCU_Tem, -190);
    lv_obj_set_y(ui_L_MCU_Tem, -80);
    lv_obj_set_align(ui_L_MCU_Tem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_L_MCU_Tem, "00");
    lv_obj_set_style_text_color(ui_L_MCU_Tem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_L_MCU_Tem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_L_MCU_Tem, &ui_font_Anton_bpp4_35, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_R_Mot_Tem = lv_label_create(ui_main_sreen);
    lv_obj_set_width(ui_R_Mot_Tem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_R_Mot_Tem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_R_Mot_Tem, 190);
    lv_obj_set_y(ui_R_Mot_Tem, -80);
    lv_obj_set_align(ui_R_Mot_Tem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_R_Mot_Tem, "00");
    lv_obj_set_style_text_color(ui_R_Mot_Tem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_R_Mot_Tem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_R_Mot_Tem, &ui_font_Anton_bpp4_35, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_R_MCU_Tem = lv_label_create(ui_main_sreen);
    lv_obj_set_width(ui_R_MCU_Tem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_R_MCU_Tem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_R_MCU_Tem, 310);
    lv_obj_set_y(ui_R_MCU_Tem, -80);
    lv_obj_set_align(ui_R_MCU_Tem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_R_MCU_Tem, "00");
    lv_obj_set_style_text_color(ui_R_MCU_Tem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_R_MCU_Tem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_R_MCU_Tem, &ui_font_Anton_bpp4_35, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CAR_Mode = lv_label_create(ui_main_sreen);
    lv_obj_set_width(ui_CAR_Mode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CAR_Mode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CAR_Mode, 0);
    lv_obj_set_y(ui_CAR_Mode, 15);
    lv_obj_set_align(ui_CAR_Mode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CAR_Mode, "Linear Accrleration");
    lv_obj_set_style_text_color(ui_CAR_Mode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CAR_Mode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CAR_Mode, &ui_font_Anton_bpp4_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOC = lv_label_create(ui_main_sreen);
    lv_obj_set_width(ui_SOC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SOC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SOC, -300);
    lv_obj_set_y(ui_SOC, 120);
    lv_obj_set_align(ui_SOC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SOC, "00%");
    lv_obj_set_style_text_color(ui_SOC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SOC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SOC, &ui_font_Anton_bpp4_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time_used = lv_label_create(ui_main_sreen);
    lv_obj_set_width(ui_time_used, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time_used, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time_used, -100);
    lv_obj_set_y(ui_time_used, 120);
    lv_obj_set_align(ui_time_used, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time_used, "00:00");
    lv_obj_set_style_text_color(ui_time_used, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time_used, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time_used, &ui_font_Anton_bpp4_35, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lap_time = lv_label_create(ui_main_sreen);
    lv_obj_set_width(ui_lap_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lap_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lap_time, 300);
    lv_obj_set_y(ui_lap_time, 120);
    lv_obj_set_align(ui_lap_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lap_time, "00:00");
    lv_obj_set_style_text_color(ui_lap_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lap_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lap_time, &ui_font_Anton_bpp4_35, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_best_time = lv_label_create(ui_main_sreen);
    lv_obj_set_width(ui_best_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_best_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_best_time, 100);
    lv_obj_set_y(ui_best_time, 120);
    lv_obj_set_align(ui_best_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_best_time, "00:00");
    lv_obj_set_style_text_color(ui_best_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_best_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_best_time, &ui_font_Anton_bpp4_35, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_L_Battery_Alr = lv_img_create(ui_main_sreen);
    lv_img_set_src(ui_L_Battery_Alr, &ui_img_2095113354);
    lv_obj_set_width(ui_L_Battery_Alr, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_L_Battery_Alr, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_L_Battery_Alr, -300);
    lv_obj_set_y(ui_L_Battery_Alr, 15);
    lv_obj_set_align(ui_L_Battery_Alr, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_L_Battery_Alr, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_L_Battery_Alr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Iot = lv_img_create(ui_main_sreen);
    lv_img_set_src(ui_Iot, &ui_img_iot_png);
    lv_obj_set_width(ui_Iot, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Iot, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Iot, 300);
    lv_obj_set_y(ui_Iot, 15);
    lv_obj_set_align(ui_Iot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Iot, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Iot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
	lv_obj_add_flag(ui_Iot, LV_OBJ_FLAG_HIDDEN);

    ui_Sliderspeed = lv_slider_create(ui_main_sreen);
    lv_slider_set_value(ui_Sliderspeed, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Sliderspeed) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Sliderspeed, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Sliderspeed, 780);
    lv_obj_set_height(ui_Sliderspeed, 25);
    lv_obj_set_x(ui_Sliderspeed, 0);
    lv_obj_set_y(ui_Sliderspeed, -210);
    lv_obj_set_align(ui_Sliderspeed, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Sliderspeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Sliderspeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Sliderspeed, &ui_img_guage_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Sliderspeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Sliderspeed, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Sliderspeed, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Sliderspeed, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Sliderspeed, &ui_img_group_4_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Sliderspeed, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Sliderspeed, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Sliderspeed, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SliderSOC = lv_slider_create(ui_main_sreen);
    lv_slider_set_value(ui_SliderSOC, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSOC) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSOC, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSOC, 780);
    lv_obj_set_height(ui_SliderSOC, 25);
    lv_obj_set_x(ui_SliderSOC, 0);
    lv_obj_set_y(ui_SliderSOC, 200);
    lv_obj_set_align(ui_SliderSOC, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderSOC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSOC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderSOC, &ui_img_guage_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_SliderSOC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderSOC, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderSOC, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSOC, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderSOC, &ui_img_group_5_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderSOC, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderSOC, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSOC, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_main_sreen);
    lv_img_set_src(ui_Image1, &ui_img_line1_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -185);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_main_sreen);
    lv_img_set_src(ui_Image2, &ui_img_line1_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, -40);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_main_sreen);
    lv_img_set_src(ui_Image3, &ui_img_line1_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Image3, 0);
    lv_obj_set_y(ui_Image3, 70);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_main_sreen);
    lv_img_set_src(ui_Image4, &ui_img_line1_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Image4, 0);
    lv_obj_set_y(ui_Image4, 175);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_main_sreen);
    lv_img_set_src(ui_Image5, &ui_img_line2_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 145
    lv_obj_set_x(ui_Image5, -130);
    lv_obj_set_y(ui_Image5, -113);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_main_sreen);
    lv_img_set_src(ui_Image6, &ui_img_line2_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 145
    lv_obj_set_x(ui_Image6, 130);
    lv_obj_set_y(ui_Image6, -113);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_main_sreen);
    lv_img_set_src(ui_Image7, &ui_img_line3_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 110
    lv_obj_set_x(ui_Image7, -200);
    lv_obj_set_y(ui_Image7, 15);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_main_sreen);
    lv_img_set_src(ui_Image8, &ui_img_line3_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 110
    lv_obj_set_x(ui_Image8, 200);
    lv_obj_set_y(ui_Image8, 15);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_img_create(ui_main_sreen);
    lv_img_set_src(ui_Image9, &ui_img_line4_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 105
    lv_obj_set_x(ui_Image9, -200);
    lv_obj_set_y(ui_Image9, 120);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_main_sreen);
    lv_img_set_src(ui_Image10, &ui_img_line4_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 105
    lv_obj_set_x(ui_Image10, 0);
    lv_obj_set_y(ui_Image10, 122);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_img_create(ui_main_sreen);
    lv_img_set_src(ui_Image11, &ui_img_line4_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 105
    lv_obj_set_x(ui_Image11, 200);
    lv_obj_set_y(ui_Image11, 122);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_img_create(ui_main_sreen);
    lv_img_set_src(ui_Image12, &ui_img_line5_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 271
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_x(ui_Image12, -265);
    lv_obj_set_y(ui_Image12, -115);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_img_create(ui_main_sreen);
    lv_img_set_src(ui_Image13, &ui_img_line5_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 271
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_x(ui_Image13, 265);
    lv_obj_set_y(ui_Image13, -115);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_img_create(ui_main_sreen);
    lv_img_set_src(ui_Image14, &ui_img_line6_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_Image14, -250);
    lv_obj_set_y(ui_Image14, -77);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image15 = lv_img_create(ui_main_sreen);
    lv_img_set_src(ui_Image15, &ui_img_line6_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_Image15, 245);
    lv_obj_set_y(ui_Image15, -77);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Sliderspeed, ui_event_Sliderspeed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderSOC, ui_event_SliderSOC, LV_EVENT_ALL, NULL);


	MQTT_INIT_OK = lv_event_register_id();
	lv_obj_add_event_cb(ui_Iot, ui_event_internet_icon, LV_EVENT_ALL, NULL);
}
