// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

static void set_value(void * bar, int32_t v)
{
    lv_bar_set_value(bar, v, LV_ANIM_OFF);
}

void ui_startup_screen_init(void)
{
    ui_startup = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_startup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_startup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_startup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LYicon = lv_img_create(ui_startup);
    lv_img_set_src(ui_LYicon, &ui_img_ly_icon_png);
    lv_obj_set_width(ui_LYicon, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_LYicon, LV_SIZE_CONTENT);    /// 134
    lv_obj_set_x(ui_LYicon, -132);
    lv_obj_set_y(ui_LYicon, -30);
    lv_obj_set_align(ui_LYicon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LYicon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LYicon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LYlabel = lv_label_create(ui_startup);
    lv_obj_set_width(ui_LYlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LYlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LYlabel, 61);
    lv_obj_set_y(ui_LYlabel, -30);
    lv_obj_set_align(ui_LYlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LYlabel, "凌云车队");
    lv_obj_set_style_text_color(ui_LYlabel, lv_color_hex(0xDE3439), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LYlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LYlabel, &ui_font_mashanzheng_60_bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sliderstartup = lv_slider_create(ui_startup);
    lv_slider_set_value(ui_Sliderstartup, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Sliderstartup) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Sliderstartup, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_Sliderstartup, 400);
    lv_obj_set_height(ui_Sliderstartup, 15);
    lv_obj_set_x(ui_Sliderstartup, -3);
    lv_obj_set_y(ui_Sliderstartup, 28);
    lv_obj_set_align(ui_Sliderstartup, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Sliderstartup, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
	
	//system start animation
	lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, ui_Sliderstartup);
    lv_anim_set_values(&a, 0, 100);//0~100进行增长
    lv_anim_set_exec_cb(&a, set_value); 
	lv_anim_set_time(&a, 3000); //2s时长
	lv_anim_start(&a);
	

    lv_obj_set_style_radius(ui_Sliderstartup, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Sliderstartup, lv_color_hex(0x2095F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Sliderstartup, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Sliderstartup, lv_color_hex(0xDE3439), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Sliderstartup, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Sliderstartup, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Sliderstartup, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

	SLIDER_LOAD_OVER = lv_event_register_id();

    lv_obj_add_event_cb(ui_Sliderstartup, ui_event_Sliderstartup, LV_EVENT_ALL, NULL);

}
