// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: demo

#include "../ui.h"

static void set_value(void * bar, int32_t v)
{
    lv_bar_set_value(bar, v, LV_ANIM_OFF);
}

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Screen1, &ui_font_Font40s4pbpp, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 61);
    lv_obj_set_y(ui_Label4, -30);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "凌云车队");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xB6171C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image25 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image25, &ui_img_ly_icon_png);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 134
    lv_obj_set_x(ui_Image25, -132);
    lv_obj_set_y(ui_Image25, -30);
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Image25, &ui_img_ly_icon_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_Screen1);
    lv_slider_set_value(ui_Slider2, 70, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 400);
    lv_obj_set_height(ui_Slider2, 15);
    lv_obj_set_x(ui_Slider2, -3);
    lv_obj_set_y(ui_Slider2, 28);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Slider2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

	//system start animation
	lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, ui_Slider2);
    lv_anim_set_values(&a, 0, 100);//0~100进行增长
    lv_anim_set_exec_cb(&a, set_value); 
	lv_anim_set_time(&a, 3000); //2s时长
	lv_anim_start(&a);

    lv_obj_set_style_radius(ui_Slider2, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x2095F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider2, lv_color_hex(0xDE3439), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider2, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

	SLIDER_LOAD_OVER = lv_event_register_id();
    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);

}
